/* soapinterop2CProxy.h
   Generated by gSOAP 2.7.9 from interop_all.h
   Copyright(C) 2000-2006, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapinterop2C_H
#define soapinterop2C_H
#include "soapH.h"
class interop2C
{   public:
	struct soap *soap;
	const char *endpoint;
	interop2C()
	{ soap = soap_new(); endpoint = "http://www.cs.fsu.edu/~engelen/interop2C.cgi"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"s", "http://soapinterop.org/xsd", NULL, NULL},
	{"ns", "http://soapinterop.org/", NULL, NULL},
	{"h", "http://soapinterop.org/echoheader/", NULL, NULL},
	{"m", "http://soapinterop.org/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	virtual ~interop2C() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	virtual int m__echoVoid(struct m__echoVoidResponse &result) { return soap ? soap_call_m__echoVoid(soap, endpoint, NULL, result) : SOAP_EOM; };
};
#endif
