/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Defined if JavaScript should be dynamically opened at run-time */
/* #undef DLOPEN_JAVASCRIPT */

/* Defined if dynamic add-ons are enabled */
/* #undef DYNAMIC_ADD_ONS */

/* Defined if bookmark support is enabled */
#define ENABLE_BOOKMARKS 1

/* If we support protocols trough local CGI */
/* #undef ENABLE_CGI */

/* Defined if font substitution is enabled */
/* #undef ENABLE_FONTSUBS */

/* If we want support for the FTP protocol */
#define ENABLE_FTP 1

/* Defined if JavaScript support is enabled */
#define ENABLE_JAVASCRIPT 1

/* Defined if JavaScript can be extended */
/* #undef ENABLE_JS_HOSTEXTEND */

/* Defined if we want printing support */
/* #undef ENABLE_PRINTING */

/* Defined if we support KParts::ReadWritePart */
/* #undef ENABLE_READWRITE */

/* Defined if local sidebar support is enabled */
/* #undef ENABLE_SIDEBAR */

/* Defined if user interface comes from a XML file */
/* #undef ENABLE_XMLUI */

/* Defined if the executable exports its symbols */
/* #undef EXPORT_SYMBOLS */

/* Define if getaddrinfo returns AF_UNIX sockets */
#define GETADDRINFO_RETURNS_UNIX 1

/* Define to the type of elements in the array set by `getgroups'. Usually
   this is either `int' or `gid_t'. */
#define GETGROUPS_T gid_t

/* You _must_ have bool */
#define HAVE_BOOL 1

/* Define if getaddrinfo is broken and should be replaced */
/* #undef HAVE_BROKEN_GETADDRINFO */

/* Define if you have the CoreAudio API */
/* #undef HAVE_COREAUDIO */

/* Define to 1 if you have the <crt_externs.h> header file. */
/* #undef HAVE_CRT_EXTERNS_H */

/* Defines if your system has the crypt function */
#define HAVE_CRYPT 1

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#define HAVE_DIRENT_H 1

/* Define if you have dlfcn */
#define HAVE_DLFCN 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <dl.h> header file. */
/* #undef HAVE_DL_H */

/* Define to 1 if you have the <float.h> header file. */
#define HAVE_FLOAT_H 1

/* Define to 1 if you have the `freeaddrinfo' function. */
#define HAVE_FREEADDRINFO 1

/* Define if you have finite */
#define HAVE_FUNC_FINITE 1

/* Define if you have isinf */
#define HAVE_FUNC_ISINF 1

/* Define if you have isnan */
#define HAVE_FUNC_ISNAN 1

/* Define if you have _finite */
/* #undef HAVE_FUNC__FINITE */

/* Define to 1 if you have the `gai_strerror' function. */
#define HAVE_GAI_STRERROR 1

/* Define if getaddrinfo is present */
#define HAVE_GETADDRINFO 1

/* Define if you have getdomainname */
#define HAVE_GETDOMAINNAME 1

/* Define if you have the getdomainname prototype */
#define HAVE_GETDOMAINNAME_PROTO 1

/* Define to 1 if you have the `gethostbyname2' function. */
#define HAVE_GETHOSTBYNAME2 1

/* Define to 1 if you have the `gethostbyname2_r' function. */
#define HAVE_GETHOSTBYNAME2_R 1

/* Define to 1 if you have the `gethostbyname_r' function. */
#define HAVE_GETHOSTBYNAME_R 1

/* Define if you have gethostname */
#define HAVE_GETHOSTNAME 1

/* Define if you have the gethostname prototype */
#define HAVE_GETHOSTNAME_PROTO 1

/* Define to 1 if you have the `getnameinfo' function. */
#define HAVE_GETNAMEINFO 1

/* Define to 1 if you have the `getpeername' function. */
#define HAVE_GETPEERNAME 1

/* Define to 1 if you have the `getsockname' function. */
#define HAVE_GETSOCKNAME 1

/* Define to 1 if you have the `getsockopt' function. */
#define HAVE_GETSOCKOPT 1

/* Define to 1 if you have the <ieeefp.h> header file. */
/* #undef HAVE_IEEEFP_H */

/* Define to 1 if you have the `inet_ntop' function. */
#define HAVE_INET_NTOP 1

/* Define to 1 if you have the `inet_pton' function. */
#define HAVE_INET_PTON 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if you have libjpeg */
#define HAVE_LIBJPEG 1

/* Define if you have libpng */
#define HAVE_LIBPNG 1

/* Define if you have a working libpthread (will enable threaded code) */
/* #undef HAVE_LIBPTHREAD */

/* Define if you have libz */
#define HAVE_LIBZ 1

/* Define to 1 if long double works and has more range or precision than
   double. */
/* #undef HAVE_LONG_DOUBLE */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `mkstemp' function. */
#define HAVE_MKSTEMP 1

/* Define to 1 if you have the `mkstemps' function. */
/* #undef HAVE_MKSTEMPS */

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define if your system needs _NSGetEnviron to set up the environment */
/* #undef HAVE_NSGETENVIRON */

/* Define if you have OpenSSL < 0.9.6 */
/* #undef HAVE_OLD_SSL_API */

/* Define to 1 if you have the <paths.h> header file. */
#define HAVE_PATHS_H 1

/* Define if you have pcreposix libraries and header files. */
/* #undef HAVE_PCREPOSIX */

/* Define to 1 if you have the <pthread/linuxthreads/pthread.h> header file.
   */
/* #undef HAVE_PTHREAD_LINUXTHREADS_PTHREAD_H */

/* Define if you have random */
#define HAVE_RANDOM 1

/* Define if you have the random prototype */
#define HAVE_RANDOM_PROTO 1

/* Define if you have res_init */
#define HAVE_RES_INIT 1

/* Define if you have the res_init prototype */
#define HAVE_RES_INIT_PROTO 1

/* Define to 1 if you have the `setenv' function. */
#define HAVE_SETENV 1

/* Define if you have shload */
/* #undef HAVE_SHLOAD */

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define if we have struct sockaddr_in6 in netinet/in.h */
#define HAVE_SOCKADDR_IN6 1

/* Define if this system already has sin6_scope_id in sockaddr_in6 */
#define HAVE_SOCKADDR_IN6_SCOPE_ID 1

/* Define if struct sockaddr has member sa_len */
/* #undef HAVE_SOCKADDR_SA_LEN */

/* Define to 1 if you have the `socket' function. */
#define HAVE_SOCKET 1

/* Define if you have srandom */
#define HAVE_SRANDOM 1

/* Define if you have the srandom prototype */
#define HAVE_SRANDOM_PROTO 1

/* If we are going to use OpenSSL */
/* #undef HAVE_SSL */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <stropts.h> header file. */
#define HAVE_STROPTS_H 1

/* Define if netdb.h defines struct addrinfo */
#define HAVE_STRUCT_ADDRINFO 1

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H 1

/* Define to 1 if you have the <sys/select.h> header file. */
#define HAVE_SYS_SELECT_H 1

/* Define to 1 if you have the <sys/sockio.h> header file. */
/* #undef HAVE_SYS_SOCKIO_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/stropts.h> header file. */
#define HAVE_SYS_STROPTS_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define if sys/stat.h declares S_ISSOCK. */
#define HAVE_S_ISSOCK 1

/* C++ compiler supports template repository */
#define HAVE_TEMPLATE_REPOSITORY 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `unsetenv' function. */
#define HAVE_UNSETENV 1

/* Define if you have usleep */
#define HAVE_USLEEP 1

/* Define if you have the usleep prototype */
#define HAVE_USLEEP_PROTO 1

/* Define to 1 if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* The prefix to use as fallback */
#define KDEDIR "/usr/local/kde"

/* Suffix for lib directories */
#define KDELIBSUFF ""

/* Define a safe value for MAXPATHLEN */
#define KDEMAXPATHLEN 4096

/* Lookup mode for IPv6 addresses: 0 for always, 1 for check and 2 for
   disabled */
#define KDE_IPV6_LOOKUP_MODE 0

/* Defined if scrollbars in KHTML are disabled */
/* #undef KHTML_NO_SCROLLBARS */

/* Defined if selections in KHTML are disabled */
/* #undef KHTML_NO_SELECTION */

/* Defined if we debug the KJS memory (de)allocations */
/* #undef KJS_DEBUG_MEM */

/* dlopen the SSL libraries at run-time */
#define KONQ_DYNAMIC_SSL 1

/* Defined because we are building the embedded version */
#define KONQ_EMBEDDED 1

/* use kiosk gui */
/* #undef KONQ_GUI_KIOSK */

/* use qpe gui */
#define KONQ_GUI_QPE 1

/* use x11 gui */
/* #undef KONQ_GUI_X11 */

/* Name of package */
#define PACKAGE "konqueror-embedded"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Defined if command line options are parsed */
#define PARSE_CMDLINE 1

/* The size of a `char', as computed by sizeof. */
#define SIZEOF_CHAR 1

/* The size of a `char *', as computed by sizeof. */
#define SIZEOF_CHAR_P 4

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* The size of a `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* If we support sorting directory listings */
/* #undef SORT_DIRLIST */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Defined if large icons are used in toolbar */
/* #undef USE_LARGE_ICONS */

/* Version number of package */
#define VERSION "0.2"

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/*
 * jpeg.h needs HAVE_BOOLEAN, when the system uses boolean in system
 * headers and I'm too lazy to write a configure test as long as only
 * unixware is related
 */
#ifdef _UNIXWARE
#define HAVE_BOOLEAN
#endif



/*
 * AIX defines FD_SET in terms of bzero, but fails to include <strings.h>
 * that defines bzero.
 */

#if defined(_AIX)
#include <strings.h>
#endif



#if !defined(HAVE_GETDOMAINNAME_PROTO)
#ifdef __cplusplus
extern "C"
#endif
int getdomainname (char *, unsigned int);
#endif



#if !defined(HAVE_GETHOSTNAME_PROTO)
#ifdef __cplusplus
extern "C"
#endif
int gethostname (char *, unsigned int);
#endif



#if !defined(HAVE_RANDOM_PROTO)
#ifdef __cplusplus
extern "C"
#endif
long int random(void);
#endif



#if !defined(HAVE_RES_INIT_PROTO)
#ifdef __cplusplus
extern "C"
#endif
int res_init (void);
#endif



#if !defined(HAVE_SRANDOM_PROTO)
#ifdef __cplusplus
extern "C"
#endif
void srandom(unsigned int);
#endif



#if !defined(HAVE_USLEEP_PROTO)
#ifdef __cplusplus
extern "C"
#endif
int usleep (unsigned int);
#endif



#ifndef HAVE_S_ISSOCK
#define HAVE_S_ISSOCK
#define S_ISSOCK(mode) (1==0)
#endif



/*
 * On HP-UX, the declaration of vsnprintf() is needed every time !
 */

#if !defined(HAVE_VSNPRINTF) || defined(hpux)
#if __STDC__
#include <stdarg.h>
#include <stdlib.h>
#else
#include <varargs.h>
#endif
#ifdef __cplusplus
extern "C"
#endif
int vsnprintf(char *str, size_t n, char const *fmt, va_list ap);
#ifdef __cplusplus
extern "C"
#endif
int snprintf(char *str, size_t n, char const *fmt, ...);
#endif



#if defined(__SVR4) && !defined(__svr4__)
#define __svr4__ 1
#endif


/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef gid_t */

/* Compatibility define */
#define ksize_t socklen_t

/* Define the real type of socklen_t */
/* #undef socklen_t */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef uid_t */
/* this is included everywhere anyway (mostly indirecty)
   and we need it for socklen_t being always available */
#include <sys/types.h>

/* provide a definition for a 32 bit entity, usable as a typedef, possibly
   extended by "unsigned" */
/* #undef INT32_BASETYPE */
#ifdef SIZEOF_INT
#if SIZEOF_INT == 4
#define INT32_BASETYPE int
#endif
#endif
#if !defined(INT32_BASETYPE) && defined(SIZEOF_LONG)
#if SIZEOF_LONG == 4
#define INT32_BASETYPE long
#endif
#endif
#ifndef INT32_BASETYPE
#define INT32_BASETYPE int
#endif

/* this is needed for Solaris and others */
#ifndef HAVE_GETDOMAINNAME_PROTO
#define HAVE_GETDOMAINNAME_PROTO
#ifdef __cplusplus
extern "C"
#endif
int getdomainname (char *Name, int Namelen);
#endif

#ifndef HAVE_GETHOSTNAME_PROTO
#define HAVE_GETHOSTNAME_PROTO
#ifdef __cplusplus
extern "C"
#endif
int gethostname (char *Name, int Namelen);
#endif

/*
 * jpeg.h needs HAVE_BOOLEAN, when the system uses boolean in system
 * headers and I'm too lazy to write a configure test as long as only
 * unixware is related
 */
#ifdef _UNIXWARE
#define HAVE_BOOLEAN
#endif

/* random() returns a value between 0 and RANDOM_MAX.
 * RANDOM_MAX is needed to generate good random numbers. (Nicolas)
 */
#ifndef HAVE_RANDOM
#define HAVE_RANDOM
#define RANDOM_MAX 2^31
#ifdef __cplusplus
extern "C"
#endif
long int random(void); /* defined in fakes.c */
#ifdef __cplusplus
extern "C"
#endif
void srandom(unsigned int seed);
#else
/* normal random() */
#define RANDOM_MAX RAND_MAX
#endif

#ifndef HAVE_S_ISSOCK
#define HAVE_S_ISSOCK
#define S_ISSOCK(mode) (1==0)
#endif

/* this is for Tru64 Unix (alias OSF, alias Digital Unix) */

#ifdef __osf__
#if !defined(__STDC__) || !__STDC__
#define __STDC__  1
#endif
#define SOL_TCP 6
typedef unsigned int   u_int32_t;
typedef unsigned char  uint8_t;
typedef unsigned short uint16_t;
typedef unsigned int   uint32_t;
#include <stdarg.h>          /* va_start and the like */
#define RTLD_GLOBAL 0        /* dlopen flag not known under Tru64  */
#ifndef HAVE_USLEEP          /* usleep not defined in Tru64        */
#ifdef __cplusplus
extern "C" void usleep(unsigned int);
#else
void usleep(unsigned int);
#endif
#endif
#ifdef __cplusplus
extern "C" {
#endif
#include <sys/mount.h>
int getmntinfo(struct statfs **mntbufp, int flags);
#include <sys/fs_types.h>    /* for mnt_names[] */
#ifdef __cplusplus
}
#endif
#endif

/*
 * On HP-UX, the declaration of vsnprintf() is needed every time !
 */

#if !defined(HAVE_VSNPRINTF) || defined(hpux)
#if __STDC__
#include <stdarg.h>
#include <stdlib.h>
#else
#include <varargs.h>
#endif
#ifdef __cplusplus
extern "C"
#endif
int vsnprintf(char *str, size_t n, char const *fmt, va_list ap);
#ifdef __cplusplus
extern "C"
#endif
int snprintf(char *str, size_t n, char const *fmt, ...);
#endif

/* Bloody HP-UX (10.20) headers don't define all the res_xxx functions,
   although they are there.  */
#if defined(hpux) && defined(HAVE_RES_INIT)
#ifdef __cplusplus
extern "C"
#endif
void res_init (void);
#endif

#if !defined(HAVE_SETENV)
#ifdef __cplusplus
extern "C"
#endif
int setenv(const char *name, const char *value, int overwrite);
#endif

#if !defined(HAVE_UNSETENV)
#ifdef __cplusplus
extern "C"
#endif
int unsetenv(const char *name);
#endif

#if !defined(HAVE_MKSTEMPS)
#ifdef __cplusplus
extern "C"
#endif
int mkstemps (char* _template, int suffix_len); /* defined in fakes.c */
#endif


#if !defined(HAVE_MKSTEMP)
#define HAVE_MKSTEMP
#ifdef __cplusplus
extern "C"
#endif
int mkstemp (char* _template); /* defined in fakes.c */
#endif

/*
 * AIX defines FD_SET in terms of bzero, but fails to include <strings.h>
 * that defines bzero.
 */

#if defined(_AIX)
#include <strings.h>
#endif

/*
 * AIX prior to 5.1 fails to provide a declaration for initgroups()
 */
#if defined(_AIX) && !defined(_AIX51)
#include <grp.h>
#ifdef __cplusplus
extern "C"
#endif
int initgroups(char *, gid_t);  /* missing declaration in AIX < 5.1 */
#endif

/*
 * Steven Schultz <sms@to.gd-es.com> tells us :
 * BSD/OS 4.2 doesn't have a prototype for openpty in its system header files
 */
#ifdef __bsdi__
__BEGIN_DECLS
int openpty(int *, int *, char *, struct termios *, struct winsize *);
__END_DECLS
#endif

