/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT tokliBIOS.cdb */

/*  Include Header Files  */
#include <std.h>
#include <prd.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>
#include <sem.h>

#ifdef __cplusplus
extern "C" {
#endif

extern PRD_Obj PRD0;
extern PRD_Obj PRD1;
extern SWI_Obj PRD_swi;
extern SWI_Obj KNL_swi;
extern TSK_Obj TSK_idle;
extern TSK_Obj TSK_sleep;
extern TSK_Obj TSK_super;
extern LOG_Obj LOG_system;
extern SEM_Obj SEM_super;
extern SEM_Obj SEM_ipbuf_sys_da;
extern SEM_Obj SEM_fb;


#ifdef __cplusplus
}
#endif /* extern "C" */
